# Generated by Django 2.2.5 on 2021-01-09 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planos', '0001_initial'),
        ('mio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('tempPermanencia', models.TimeField(blank=True, null=True)),
                ('event', models.CharField(max_length=15)),
                ('action', models.CharField(max_length=15)),
                ('portout', models.IntegerField()),
                ('portin', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=15, null=True)),
                ('mio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mio.Mio')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planos.Plano')),
            ],
        ),
    ]
