# Generated by Django 2.2.5 on 2021-01-09 13:19

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('foto', models.FileField(upload_to=accounts.models.get_file_path)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
