# Generated by Django 2.2.5 on 2021-01-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=15)),
                ('temperature', models.IntegerField()),
                ('battery', models.IntegerField()),
                ('statusAssociacao', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
