# Generated by Django 2.2.5 on 2021-01-09 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaborator', '0001_initial'),
        ('planos', '0001_initial'),
        ('ativo', '0001_initial'),
        ('tag', '0001_initial'),
        ('anchor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociacaoCollaborator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborator.Collaborator')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='AssociacaoAtivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ativo.Ativo')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='AssociacaoAnchor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('anchor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anchor.Anchor')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planos.Plano')),
            ],
        ),
    ]
