# Generated by Django 2.2.5 on 2021-01-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=35)),
                ('descricao', models.CharField(max_length=50)),
                ('foto', models.FileField(upload_to='planos/')),
            ],
        ),
    ]
